import { DaySchedule, Category } from './types';

// Helper to generate IDs
const uid = () => Math.random().toString(36).substr(2, 9);

export const INITIAL_ITINERARY: DaySchedule[] = [
  {
    id: 'day1',
    date: '2025-10-31',
    dayName: '10/31 (五)',
    weather: {
      location: '博多',
      temp: 19,
      condition: '秋高氣爽',
      icon: '🌤️',
      clothing: '天氣舒適，早晚微涼'
    },
    activities: [
      {
        id: uid(),
        time: '04:00',
        title: '機場接送',
        location: '台北家中',
        category: Category.Transport,
        cost: 0,
        currency: 'TWD',
        notes: '安捷一樓大廳集合',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '09:00',
        title: '抵達 & 太宰府天滿宮',
        location: '太宰府天滿宮',
        category: Category.Sightseeing,
        cost: 0,
        currency: 'JPY',
        notes: '學問之神，必吃梅枝餅',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '11:00',
        title: '竈門神社',
        location: '竈門神社',
        category: Category.Sightseeing,
        cost: 0,
        currency: 'JPY',
        notes: '鬼滅之刃聖地巡禮',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '12:00',
        title: '午餐：炉端ノいとおかし',
        location: 'Robata no Itookashi',
        category: Category.Food,
        cost: 3000,
        currency: 'JPY',
        notes: '已預約 12:00',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '14:00',
        title: '大國藥妝採購',
        location: '大國藥妝',
        category: Category.Shopping,
        cost: 10000,
        currency: 'JPY',
        notes: '免稅購物',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '16:00',
        title: '博多車站超市',
        location: '博多車站',
        category: Category.Shopping,
        cost: 2000,
        currency: 'JPY',
        notes: '買晚上零食',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '19:30',
        title: '晚餐：竹乃屋',
        location: '竹乃屋 博多巴士總站店',
        category: Category.Food,
        cost: 4000,
        currency: 'JPY',
        notes: '已預約 19:30，皮卷必點',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '22:00',
        title: '宵夜：努努雞',
        location: '努努雞',
        category: Category.Food,
        cost: 1500,
        currency: 'JPY',
        notes: '傳說中的冷凍炸雞',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '23:00',
        title: 'Hotel Forza Hakata',
        location: 'Hotel Forza Hakata Station Chikushiguchi II',
        category: Category.Accommodation,
        cost: 0,
        currency: 'JPY',
        notes: 'Check-in 休息',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'day2',
    date: '2025-11-01',
    dayName: '11/01 (六)',
    weather: {
      location: '由布院',
      temp: 16,
      condition: '晴時多雲',
      icon: '⛅',
      clothing: '山區涼爽，建議薄外套'
    },
    activities: [
      {
        id: uid(),
        time: '08:00',
        title: 'Dacomecca 麵包店',
        location: 'Dacomecca',
        category: Category.Food,
        cost: 2000,
        currency: 'JPY',
        notes: '當隔天早餐',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '09:17',
        title: '由布院之森',
        location: '博多車站',
        category: Category.Transport,
        cost: 4500,
        currency: 'JPY',
        notes: '已預約 09:17 發車 -> 11:32 抵達',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '12:00',
        title: '午餐：由布まぶし 心',
        location: 'Yufu Mabushi Shin',
        category: Category.Food,
        cost: 3500,
        currency: 'JPY',
        notes: '釜飯，車站旁或金鱗湖旁',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '13:30',
        title: '由布院花卉村',
        location: 'Yufuin Floral Village',
        category: Category.Sightseeing,
        cost: 1000,
        currency: 'JPY',
        notes: '童話風格，貓頭鷹之森',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '14:30',
        title: '金鱗湖',
        location: '金鱗湖',
        category: Category.Sightseeing,
        cost: 0,
        currency: 'JPY',
        notes: '湖中鳥居，夢幻倒影',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '15:30',
        title: '點心：shiitakemonster',
        location: 'Shiitake Monster',
        category: Category.Food,
        cost: 800,
        currency: 'JPY',
        notes: '香菇點心',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '18:00',
        title: '晚餐：You me Town',
        location: 'You me Town Beppu',
        category: Category.Food,
        cost: 3000,
        currency: 'JPY',
        notes: '超市覓食',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '20:00',
        title: 'MURE Beppu',
        location: 'MURE Beppu',
        category: Category.Accommodation,
        cost: 0,
        currency: 'JPY',
        notes: '溫泉飯店',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'day3',
    date: '2025-11-02',
    dayName: '11/02 (日)',
    weather: {
      location: '別府',
      temp: 17,
      condition: '多雲',
      icon: '☁️',
      clothing: '氣候宜人，適合戶外活動'
    },
    activities: [
      {
        id: uid(),
        time: '09:00',
        title: '別府地獄巡禮',
        location: '海地獄',
        category: Category.Sightseeing,
        cost: 2000,
        currency: 'JPY',
        notes: '海地獄、血池地獄、灶地獄',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '12:00',
        title: '午餐：地獄蒸工房',
        location: 'Jigoku Mushi Kobo Kannawa',
        category: Category.Food,
        cost: 2500,
        currency: 'JPY',
        notes: '體驗地熱蒸食',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '14:00',
        title: '竹瓦溫泉沙浴',
        location: '竹瓦溫泉',
        category: Category.Sightseeing,
        cost: 1500,
        currency: 'JPY',
        notes: '百年歷史砂湯',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '17:00',
        title: '巴士回博多',
        location: '別府北濱巴士站',
        category: Category.Transport,
        cost: 3250,
        currency: 'JPY',
        notes: '預約 17:00 -> 19:46 抵達',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '20:00',
        title: '晚餐：ShinShin 拉麵',
        location: 'ShinShin Ramen Hakata',
        category: Category.Food,
        cost: 1200,
        currency: 'JPY',
        notes: '博多純情拉麵',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '22:00',
        title: '宵夜：AGITO HIRAO',
        location: 'Charcoal Grill AGITO HIRAO',
        category: Category.Food,
        cost: 4000,
        currency: 'JPY',
        notes: '炭火燒肉',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '23:30',
        title: 'Hotel Forza Hakata',
        location: 'Hotel Forza Hakata Station Chikushiguchi II',
        category: Category.Accommodation,
        cost: 0,
        currency: 'JPY',
        notes: '最後一晚',
        isCompleted: false,
      },
    ],
  },
  {
    id: 'day4',
    date: '2025-11-03',
    dayName: '11/03 (一)',
    weather: {
      location: '博多',
      temp: 20,
      condition: '晴朗',
      icon: '☀️',
      clothing: '陽光普照，適合逛街'
    },
    activities: [
      {
        id: uid(),
        time: '09:00',
        title: 'I\'m donut?',
        location: 'I\'m donut? Fukuoka',
        category: Category.Food,
        cost: 1500,
        currency: 'JPY',
        notes: '超人氣排隊甜甜圈',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '10:30',
        title: 'FUK Coffee',
        location: 'FUK COFFEE',
        category: Category.Food,
        cost: 800,
        currency: 'JPY',
        notes: '航空主題咖啡',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '12:00',
        title: '午餐：麵屋石井',
        location: 'Menya ISHII',
        category: Category.Food,
        cost: 1200,
        currency: 'JPY',
        notes: '拉麵/沾麵',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '13:30',
        title: '博多運河城',
        location: 'Canal City Hakata',
        category: Category.Shopping,
        cost: 0,
        currency: 'JPY',
        notes: '噴泉秀 & 逛街',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '15:00',
        title: '伴手禮：Full Full',
        location: 'The Full Full Hakata',
        category: Category.Food,
        cost: 2000,
        currency: 'JPY',
        notes: '明太子法棍',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '16:00',
        title: '早晚餐：肉一燒肉',
        location: 'Yakiniku Nikuichi Hakata',
        category: Category.Food,
        cost: 5000,
        currency: 'JPY',
        notes: '已預約 16:00，CP值超高',
        isCompleted: false,
      },
      {
        id: uid(),
        time: '22:20',
        title: '機場接機',
        location: '台北',
        category: Category.Transport,
        cost: 0,
        currency: 'TWD',
        notes: '溫暖的家',
        isCompleted: false,
      },
    ],
  },
];